[package]
name = "cargo-zigbuild"
version = "0.7.1"
edition = "2018"
description = "Compile Cargo project with zig as linker"
license = "MIT"
keywords = ["zig", "cargo"]
readme = "README.md"
repository = "https://github.com/messense/cargo-zigbuild"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
cargo_metadata = "0.14.2"
clap = { version = "3.1.2", features = ["derive", "env", "wrap_help"] }
dirs = "4.0.0"
fs-err = "2.6.0"
path-slash = "0.1.4"
rustc_version = "0.4.0"
semver = "1.0.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
target-lexicon = "0.12.3"
